In [1]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from datetime import timedelta
from timeit import default_timer as timer
from math import sqrt

from random import choices
from scipy.linalg import null_space
from scipy.optimize import minimize

from PIL import ImageDraw

In [2]:
img_l = np.asanyarray(Image.open("../myL.jpg").convert("RGB")).astype(np.int)
img_r = np.asanyarray(Image.open("../myL.jpg").convert("RGB")).astype(np.int)
img_l = img_l[::10,::10]
img_r = img_r[::10,::10]

img_shift = np.load("../lab1/img_shift.npy")

bestF = np.load("../lab2/bestF.npy")

In [3]:
img_l.shape

(195, 260, 3)

In [4]:
scale = 10
pixel_size = 1.12e-3
pixel_size *= scale
focal = 3
width = img_r.shape[1]
height = img_r.shape[0]

In [5]:
K = np.array([[focal/pixel_size, 0, width/2],
              [0, focal/pixel_size, height/2],
              [0, 0, 1]])
K

array([[267.85714286,   0.        , 130.        ],
       [  0.        , 267.85714286,  97.5       ],
       [  0.        ,   0.        ,   1.        ]])

In [6]:
bestF

array([[ 8.55854749e-15,  6.91289031e-13, -3.02955607e-01],
       [-6.45401668e-13,  4.18780136e-14, -6.44751676e-01],
       [ 3.02955607e-01,  6.52519769e-01,  2.36150012e+00]])

In [7]:
E = np.dot(K.T, np.dot(bestF, K))
E

array([[ 6.14053949e-10,  4.95982245e-08, -8.11488233e+01],
       [-4.63059232e-08,  3.00464065e-09, -1.72701342e+02],
       [ 8.11488233e+01,  1.74782081e+02,  3.11888914e+00]])

In [9]:
U, D, T = np.linalg.svd(E)
print(*map(lambda x: round(x,2), D))

193.59 189.94 0.0


In [37]:
2*np.dot(E, E.T) - np.eye(3)*np.trace(np.dot(E, E.T))

array([[-4.84696391e+08,  2.25021468e+08, -4.53419345e+04],
       [ 2.25021468e+08, -1.11537528e+08, -9.65282825e+04],
       [-4.53419345e+04, -9.65282825e+04,  5.80454871e+06]])

Game Over